services:
  - type: web
    name: server
    env: python
    buildCommand: cd server && pipenv install
    startCommand: cd server && pipenv run gunicorn --bind 0.0.0.0:$PORT app:app

  - type: web
    name: client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist