name: Deploy to Render
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Render
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}